title: Agent Arxiv Daily
description: Automatically Update Agent Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/Ultraclr/agent-arxiv-daily
  another_url: https://github.com/Ultraclr/agent-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: Ultraclr

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag

# Keep static HTML and resources intact
keep_files:
  - papers.html
  - resources
