# Weekly trends analysis workflow

name: Weekly Trends Analysis

on:
  # Run every Sunday at 00:00 UTC
  schedule:
    - cron: "0 0 * * 0"
  # Allow manual trigger
  workflow_dispatch:

env:
  GITHUB_USER_NAME: ultraclr
  GITHUB_USER_EMAIL: longrongchen@163.com


jobs:
  analyze_trends:
    name: Analyze Research Trends
    runs-on: ubuntu-latest
    environment: llm_client
    env:
      ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
      CRS_BASE_URL: ${{ secrets.CRS_BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai tqdm

      - name: Analyze trends from recent papers
        run: |
          cd latex_analysis
          python analysis_recent_trends.py \
            --paper_num 30 \
            --analysis_json_path ../docs/agent-arxiv-daily-analysis.json \
            --saved_path ../docs/agent_trends.txt

      - name: Push trends update
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Weekly Trends Analysis Update"
          files: docs/agent_trends.txt
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
